### PR TITLE
Small mistakes :P

### PR DESCRIPTION
**Pull request by MrLukeNL**
Small mistakes fixed

### CODE REVIEW

**Comment by Kalkstein** [comment]
Errorneous, wait for merge until fixed.

**Comment by wmazereeuw** [comment]
What errors Kalk?

**Comment by Kalkstein** [comment]
For reasons of consistency, we use the monarchs as "country leaders". This fix might work, but leads to the wrong direction I think.

**Comment by wmazereeuw** [comment]
What Luke here did is fine, I'll push it through since it is basically the same system as any other country, I just forgot to change fascism to imperialism, that's all. Taking Germany for example, the Kaiser Loyalists are also imperialists. Merged, thank you again Luke.

**Pull request merged**
