### PR TITLE
Netherlands focus fix

### PR DESCRIPTION
**Pull request by MrLukeNL**
2 broken focusses fixed

### CODE REVIEW

**Comment by MrLukeNL** [comment]
I tested it and it works like it should.

**Comment by wmazereeuw** [comment]
What's broken about these two focusses? Works like it should with the code we have.

**Comment by MrLukeNL** [comment]
It required you to be 2 ideologies at the same time and as far as I know this isn't possible.

**Comment by wmazereeuw** [comment]
I see, thank you for bringing this up, I'll merge your request.

**Comment by wmazereeuw** [comment]
Thanks, I'll merge your request.

**Pull request merged**
